#ifndef CONFIG_H
#define CONFIG_H

#define THORVG_VERSION_STRING "0.11.99"

#define THORVG_SW_RASTER_SUPPORT 1

#define THORVG_SVG_LOADER_SUPPORT 1

#define THORVG_PNG_LOADER_SUPPORT 1

#define THORVG_TVG_LOADER_SUPPORT 1

#define THORVG_JPG_LOADER_SUPPORT 1

#define THORVG_LOTTIE_LOADER_SUPPORT 1

// #define THORVG_LOG_ENABLED 1

#endif
